---
- name: Set up Client01
  hosts: localclient01

  tasks:
    - name: "Change the hostname"
      win_hostname:
        name: "Client01"
    
    - name: DNS
      win_shell: |
        Set-DNSClientServerAddress -InterfaceIndex (Get-Netadapter | where-object { $_.Name -like "Eth*" }).InterfaceIndex.tostring() -ServerAddresses 192.168.21.152
    
    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30

    - name: Add computer to AD
      win_shell: |
        $password = ConvertTo-SecureString 'ykpB@7@$DUQ8G-Ag' -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ('scranton.dunder-mifflin.local\m.scott', $password)
        Add-Computer -DomainName "scranton.dunder-mifflin.local" -Credential $credential

    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30

    - name: Winrm user
      win_shell: |
        net localgroup "Backup Operators" "scranton\j.halpert" /add
        net localgroup "Remote Management Users" /add scranton\k.malone
        net localgroup "Remote Management Users" /add scranton\j.halpert
        winrm quickconfig -force
    
    - name: Make share folder
      win_shell: |
        New-Item -Path "C:\Share" -ItemType Directory

    - name: Copy usernames to share
      win_copy:
        src: ./usernames.txt
        dest: C:\Share\users.txt

    - name: Do the smb
      win_shell: |
        Install-WindowsFeature -Name FS-SMB1, FS-SMB2 -IncludeAllSubFeature
        New-SmbShare -Name "Share" -Path "C:\Share" -FullAccess "Everyone" -ReadAccess "Everyone" -ChangeAccess "Everyone" -Description "Open Access Share"


    - name: No defender
      win_shell: |
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender" -Name "DisableAntiSpyware" -Value 1 -Type DWord
