---
- name: Set up Client01
  hosts: localclient01
  
  tasks:
    - name: "Change the hostname"
      win_hostname:
        name: "Client01"

- name: Set up Client02
  hosts: localclient02
  
  tasks:
    - name: "Change the hostname"
      win_hostname:
        name: "Client02"

- name: Join Computers to domain
  hosts: localclient02 localclient01

  tasks:

    - name: DNS
      win_shell: |
        Set-DNSClientServerAddress -InterfaceIndex (Get-Netadapter | where-object { $_.Name -like "Eth*" }).InterfaceIndex.tostring() -ServerAddresses 192.168.21.164
    
    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30

    - name: Add computer to AD
      win_shell: |
        $password = ConvertTo-SecureString 'ykpB@7@$DUQ8G-Ag' -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ('scranton.dunder-mifflin.local\m.scott', $password)
        Add-Computer -DomainName "scranton.dunder-mifflin.local" -Credential $credential

    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30

    - name: No defender
      win_shell: |
        Set-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender" -Name "DisableAntiSpyware" -Value 1 -Type DWord

- name: Client01 config
  hosts: localclient01
  
  tasks:
    - name: Winrm user
      win_shell: |
        net localgroup "Backup Operators" "scranton\j.halpert" /add
        net localgroup "Remote Management Users" /add scranton\k.malone
        net localgroup "Remote Management Users" /add scranton\j.halpert
        winrm quickconfig -force

- name: Client02 config
  hosts: localclient02

  tasks:
    - name: Winrm user
      win_shell: |
        net localgroup "Remote Management Users" /add scranton\d.schrute
        winrm quickconfig -force
    
    - name: NetNTLMv1
      win_shell: |
        New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Lsa" -Name "LmCompatibilityLevel" -Value 2 -PropertyType DWORD -Force