---
- name: Set up Corp-DC
  hosts: localparentdc

  tasks:
    - name: "Change the hostname"
      win_hostname:
        name: "Corporate-DC"

    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
    
    - name: Install Domain Services
      win_shell: |
        Add-WindowsFeature AD-Domain-Services
        Install-ADDSForest -DomainName "dunder-mifflin.local" -DomainNetbiosName "DUNDER-MIFFLIN" -InstallDNS -Force -SafeModeAdministratorPassword (ConvertTo-SecureString "Password123#" -AsPlainText -Force) -NoRebootOnCompletion -ForestMode "WinThreshold"
    
    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30
    


- name: Do the AD stuff
  hosts: 192.168.21.129

  vars:
    ansible_user: Administrator 
    ansible_password: Password123#
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Add site
      win_shell: |
        New-ADReplicationSite -Name "scranton"
    
    - name: Reboot if needed
      win_reboot:
        reboot_timeout: 600
        post_reboot_delay: 30

    - name: Add Domain Admin
      win_shell: |
        Import-Module ActiveDirectory
        New-ADUser -Name "David Wallace" -SamAccountName "d.wallace" -UserPrincipalName "d.wallace@dunder-mifflin.local" -GivenName "David" -Surname "Wallace" -AccountPassword (ConvertTo-SecureString "w3V!o^4:A1aN(6" -AsPlainText -Force) -Enabled $true -Path "CN=Users,DC=dunder-mifflin,DC=local"
        Add-ADGroupMember -Identity "Domain Admins" -Members "d.wallace"
        Add-ADGroupMember -Identity "Enterprise Admins" -Members "d.wallace"


# add sleep after reboot?
