- name: Copy config files
  hosts: localvpn

  tasks:
    - name: Create directory
      file:
        path: /opt/vpn-conf
        state: directory
        mode: "0755"
      
    - name: Copy server and client file
      copy:
        src: "{{ item.src }}"
        dest: /opt/vpn-conf/
        mode: "0644"
      loop:
        - { src: "/home/eljay/adctf/vpn/client.conf"}
        - { src: "/home/eljay/adctf/vpn/server.conf"}
        - { src: "/home/eljay/adctf/vpn/format-vpn-file.sh"}
  
    - name: move server files
      command: "cp /opt/easy-rsa/easyrsa3/pki/{{ item.file }} /opt/vpn-conf/"
      loop:
        - { file: "ca.crt"}
        - { file: "dh.pem"}
        - { file: "private/vpn-gateway.key"}
        - { file: "issued/vpn-gateway.crt"}

    - name: mark helper script as executable
      command: "chmod +x /opt/vpn-conf/format-vpn-file.sh"

- name: Create user access files
  hosts: localvpn
  tasks:
    - name: "gen tls"
      command: openvpn --genkey tls-auth ta.key
      become: yes
      args:
        chdir: /opt/vpn-conf